export const ENQUIRY_TYPES = [
  { value: "RESIDENTIAL AIR CONDITIONING", label: "RESIDENTIAL AIR CONDITIONING" },
  { value: "COMMERCIAL AIR CONDITIONING", label: "COMMERCIAL AIR CONDITIONING" },
  { value: "COMMERCIAL REFRIGERATION", label: "COMMERCIAL REFRIGERATION" },
  { value: "MECHANICAL SERVICES", label: "MECHANICAL SERVICES" },
  { value: "WINERY REFRIGERATION", label: "WINERY REFRIGERATION" },
  { value: "PANASONIC WARRANTY REPAIRS", label: "PANASONIC WARRANTY REPAIRS" },
  { value: "EQUIPMENT HIRE", label: "EQUIPMENT HIRE" },
  { value: "OTHER", label: "OTHER" },
] as const;

export const ENQUIRY_TYPE_VALUES = ENQUIRY_TYPES.map((t) => t.value);
