import type { GalleryImage, GallerySlot, ProjectId } from "@/lib/gallery";

function seed(
  id: string,
  slot: GallerySlot,
  url: string,
  alt: string,
  sort: number,
  projectId?: ProjectId | null
): GalleryImage {
  return { id: `seed-${id}`, slot, url, alt, sort, projectId: projectId ?? null };
}

export const SEED_IMAGES: GalleryImage[] = [
  seed("hero-bg", "hero", "/images/hero-bg.webp", "Rooftop air conditioning", 0),

  seed("about-main", "about-main", "/images/fremantle-16.webp", "Glacier Air team at work", 0),
  seed("about-left", "about-left", "/images/about-1.webp", "Refrigeration installation", 0),
  seed("about-right", "about-right", "/images/about-2.webp", "AC installation", 0),

  seed("services-ac", "services-ac", "/images/tile-air-conditioning.webp", "Air conditioning", 0),
  seed("services-ref", "services-ref", "/images/tile-refrigeration.webp", "Refrigeration", 0),
  seed("services-mech", "services-mech", "/images/tile-mechanical.webp", "Mechanical services", 0),

  seed("fremantle-7", "projects", "/images/fremantle-7.webp", "Fremantle office fitout", 0, "unassigned"),
  seed("fremantle-13", "projects", "/images/fremantle-13.webp", "Fremantle office fitout", 1, "unassigned"),
  seed("fremantle-19", "projects", "/images/fremantle-19.webp", "Fremantle office fitout", 2, "unassigned"),
  seed("refrigeration", "projects", "/images/refrigeration.webp", "Refrigeration project", 3, "unassigned"),
  seed("nikola-estate", "projects", "/images/nikola-estate.webp", "Nikola Estate", 0, "nikola"),
  seed("daiwa-foods", "projects", "/images/projects/daiwa-foods.webp", "Daiwa Foods cold storage", 0, "daiwa"),
  seed("daiwa-2", "projects", "/images/projects/daiwa-2.webp", "Daiwa Foods cold storage", 1, "daiwa"),
  seed("henley-park", "projects", "/images/projects/henley-park.webp", "Henley Park Wines chiller upgrade", 0, "henley"),
  seed("henley-2", "projects", "/images/projects/henley-2.webp", "Henley Park Wines chiller upgrade", 1, "henley"),
  seed("henley-3", "projects", "/images/projects/henley-3.webp", "Henley Park Wines chiller upgrade", 2, "henley"),
  seed("new-west-foods", "projects", "/images/projects/new-west-foods.webp", "New West Foods cold storage", 0, "new-west"),
  seed("new-west-2", "projects", "/images/projects/new-west-2.webp", "New West Foods cold storage", 1, "new-west"),
  seed("new-west-3", "projects", "/images/projects/new-west-3.webp", "New West Foods cold storage", 2, "new-west"),
  seed("nikola-1", "projects", "/images/projects/nikola-1.webp", "Nikola Estate barn AC", 1, "nikola"),
  seed("nikola-2", "projects", "/images/projects/nikola-2.webp", "Nikola Estate barn AC", 2, "nikola"),
  seed("nikola-3", "projects", "/images/projects/nikola-3.webp", "Nikola Estate barn AC", 3, "nikola"),
  seed("nikola-4", "projects", "/images/projects/nikola-4.webp", "Nikola Estate barn AC", 4, "nikola"),
  seed("primero", "projects", "/images/projects/primero.webp", "Primero HVAC installation, Pilbara", 0, "primero"),
  seed("primero-2", "projects", "/images/projects/primero-2.webp", "Primero HVAC installation, Pilbara", 1, "primero"),
  seed("shelf-subsea", "projects", "/images/projects/shelf-subsea.webp", "Shelf Subsea dive chiller overhaul", 0, "shelf"),
  seed("shelf-2", "projects", "/images/projects/shelf-2.webp", "Shelf Subsea dive chiller overhaul", 1, "shelf"),
  seed("west-cape-howe", "projects", "/images/projects/west-cape-howe.webp", "West Cape Howe winery chiller upgrade", 0, "west-cape"),
  seed("west-cape-2", "projects", "/images/projects/west-cape-2.webp", "West Cape Howe winery chiller upgrade", 1, "west-cape"),
  seed("windsor-cinema", "projects", "/images/projects/windsor-cinema.webp", "Windsor Cinema AC upgrade", 0, "windsor"),

  seed("client-alzheimers-wa", "clients", "/clients/alzheimers-wa.png", "Alzheimer’s WA", 0),
  seed("client-cancer-council", "clients", "/clients/cancer-council.png", "Cancer Council", 1),
  seed("client-sandalford", "clients", "/clients/sandalford-wines.png", "Sandalford Wines", 2),
  seed("client-pirate-life", "clients", "/clients/pirate-life.png", "Pirate Life Perth", 3),
  seed("client-altegra", "clients", "/clients/altegra.png", "Altegra Property Group", 4),
  seed("client-new-west-foods", "clients", "/clients/new-west-foods.png", "New West Foods", 5),
  seed("client-montau", "clients", "/clients/montau-lighting.png", "THE MONTAU LIGHTING", 6),
  seed("client-west-cape-howe", "clients", "/clients/west-cape-howe.png", "West Cape Howe Wines", 7),
  seed("client-oakover", "clients", "/clients/oakover-wines.png", "Oakover Wines", 8),
  seed("client-luna-palace", "clients", "/clients/luna-palace.png", "Luna Palace Cinemas", 9),
  seed("client-benara", "clients", "/clients/benara-nurseries.png", "Benara Nurseries", 10),
  seed("client-foodfolk", "clients", "/clients/foodfolk.png", "foodfolk AUSTRALIA", 11),
  seed("client-sagewood", "clients", "/clients/sagewood.png", "sagewood Early Learning", 12),
  seed("client-uplyft", "clients", "/clients/uplyft.png", "Uplyft", 13),
  seed("client-ross-scarfone", "clients", "/clients/ross-scarfone.png", "Ross Scarfone Real Estate", 14),
  seed("client-island-market", "clients", "/clients/island-market.png", "Island Market Trigg", 15),
  seed("client-tsokos", "clients", "/clients/tsokos.png", "TSOKOS", 16),
  seed("client-forest-hill", "clients", "/clients/forest-hill.png", "Forest Hill Vineyard", 17),
  seed("client-raine-horne", "clients", "/clients/raine-horne.png", "Raine & Horne Commercial", 18),
  seed("client-margaret-river", "clients", "/clients/margaret-river-vintners.png", "Margaret River Vintners", 19),
  seed("client-home-base", "clients", "/clients/home-base.png", "HOME BASE", 20),
  seed("client-cherubino", "clients", "/clients/cherubino.png", "Cherubino wines", 21),
  seed("client-accolade", "clients", "/images/clients/accolade-wines.png", "Accolade Wines", 22),
  seed("client-bower", "clients", "/images/clients/bower-wanslea.png", "Bower Wanslea", 23),
  seed("client-cancer-council-wa", "clients", "/images/clients/cancer-council-wa.png", "Cancer Council WA", 24),
  seed("client-forest-hill-vineyard", "clients", "/images/clients/forest-hill-vineyard.png", "Forest Hill Vineyard", 25),
  seed("client-home-base-perth", "clients", "/images/clients/home-base-perth.png", "Home Base Perth", 26),
  seed("client-luna-palace-cinemas", "clients", "/images/clients/luna-palace-cinemas.png", "Luna Palace Cinemas", 27),
  seed("client-primero-logo", "clients", "/images/clients/primero.png", "Primero", 28),
  seed("client-smile-time", "clients", "/images/clients/smile-time-orthodontics.png", "Smile Time Orthodontics", 29),
  seed("client-west-cape-howe-img", "clients", "/images/clients/west-cape-howe.png", "West Cape Howe Wines", 30),
];
